# Generated by Django 4.1.5 on 2023-01-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_rename_tag_invoice_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tags',
        ),
    ]
